name: Deploy to EC2

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-west-1
  EC2_INSTANCE_IP: ${{ secrets.EC2_INSTANCE_IP }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies and build
        run: |
          rm -rf node_modules && yarn install --frozen-lockfile
          npx prisma generate
          yarn build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: '.' # Include everything
          target: '/home/ubuntu/surf-tracker'

      - name: Execute deployment commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/surf-tracker
            # Save environment variables to PM2
            pm2 delete surf-tracker || true
            pm2 set surf-tracker:DATABASE_URL "${{ secrets.DATABASE_URL }}"
            pm2 set surf-tracker:DIRECT_URL "${{ secrets.DIRECT_URL }}"
            pm2 set surf-tracker:NEXTAUTH_SECRET "${{ secrets.NEXTAUTH_SECRET }}"
            pm2 set surf-tracker:NEXTAUTH_URL "${{ secrets.NEXTAUTH_URL }}"
            npx prisma generate
            npx prisma db push
            pm2 start ecosystem.config.js
            pm2 save
